/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.'
    // },
    "intro",
    "interface",
    "concepts",
    {
      type: "category",
      label: "Basic Guides",
      link: {
        type: "generated-index",
        title: "Basic Guides",
        slug: "basic_guides",
        keywords: ["basic", "guides"],
      },
      items: [
        "basic_guides/searching",
        "basic_guides/using_collections",
        "basic_guides/asset_tagging",
        "basic_guides/using_components",
        "basic_guides/running_actions",
        "basic_guides/running_workflows",
        "basic_guides/create_single_asset",
      ],
    },
    {
      type: "category",
      label: "Advanced Guides",
      link: {
        type: "generated-index",
        title: "Advanced Guides",
        slug: "advanced_guides",
        keywords: ["advanced", "guides"],
      },
      items: [
        "advanced_guides/advanced_filtering",
        "advanced_guides/creating_collections",
        "advanced_guides/creating_actions",
        "advanced_guides/creating_workflows",
        "advanced_guides/caching",
      ],
    },
    "developer",
    "feedback",
  ],
};

module.exports = sidebars;
